import React from 'react';
import { le_brand, le_seller, le_fuel, le_trans } from '../ml/encoders.ts';
import { CarInputSpecs, PRESET_CARS, PresetCar } from '../ml/presets.ts';
import { SpecSheetDivider } from './SpecSheetDivider.tsx';
import { ArrowRight, RefreshCw, CarFront, Gauge, Wrench, Sparkles } from 'lucide-react';

interface AppraisalFormProps {
  specs: CarInputSpecs;
  onChange: (field: keyof CarInputSpecs, value: any) => void;
  onSubmit: (e: React.FormEvent) => void;
  onApplyPreset: (preset: PresetCar) => void;
  onReset: () => void;
  isLoading?: boolean;
}

export const AppraisalForm: React.FC<AppraisalFormProps> = ({
  specs,
  onChange,
  onSubmit,
  onApplyPreset,
  onReset,
  isLoading = false
}) => {
  return (
    <div className="w-full text-left">
      {/* Editorial Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-mono tracking-[0.2em] text-[#38BDF8] uppercase">
            AUTOMOTIVE REGRESSION MODEL // LAB APPLET
          </span>
          <span className="text-[#8C8F94]">·</span>
          <span className="text-xs text-[#8C8F94] font-mono">RANDOM FOREST (R²: 0.879)</span>
        </div>
        <h1 className="font-serif-fraunces text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-[#F4F3F0] mb-3">
          Vehicle Resale Appraisal Desk
        </h1>
        <p className="text-sm sm:text-base text-[#8C8F94] max-w-3xl leading-relaxed">
          Input complete vehicle specifications across identity, usage condition, and mechanical output.
          Valuation is generated by an ensemble of 100 unscaled regression decision trees trained on 15,242 verified transactions.
        </p>
      </div>

      {/* Quick Test Presets Carousel */}
      <div className="mb-8 p-4 bg-[#1F2126] border border-[rgba(244,243,240,0.08)] rounded-sm">
        <div className="flex items-center justify-between gap-2 mb-3">
          <div className="flex items-center gap-2 text-xs font-mono text-[#38BDF8]">
            <Sparkles className="w-3.5 h-3.5" />
            <span className="tracking-widest uppercase">Benchmark Vehicles (One-Click Presets)</span>
          </div>
          <span className="text-[11px] text-[#8C8F94] hidden sm:inline">From cleaned CarDekho dataset</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
          {PRESET_CARS.map((preset) => {
            const isSelected = specs.brand === preset.brand &&
              specs.max_power === preset.max_power &&
              specs.vehicle_age === preset.vehicle_age &&
              specs.km_driven === preset.km_driven;

            return (
              <button
                key={preset.id}
                type="button"
                onClick={() => onApplyPreset(preset)}
                className={`text-left p-2.5 rounded border transition-all cursor-pointer ${
                  isSelected
                    ? 'border-[#38BDF8] bg-[#0284C7]/15 text-[#F4F3F0]'
                    : 'border-[rgba(244,243,240,0.08)] bg-[#17181C]/70 hover:border-[#38BDF8]/40 text-[#8C8F94] hover:text-[#F4F3F0]'
                }`}
              >
                <div className="flex items-center justify-between text-xs font-semibold text-[#F4F3F0] mb-0.5">
                  <span className="truncate pr-1">{preset.title}</span>
                  {preset.is_ground_truth_test && (
                    <span className="text-[9px] font-mono px-1 py-0.2 text-[#1E6E4F] bg-[#1E6E4F]/20 rounded shrink-0">
                      STEP 8 TEST
                    </span>
                  )}
                </div>
                <div className="text-[11px] text-[#8C8F94] flex items-center justify-between font-mono">
                  <span>Actual: ₹{(preset.actual_selling_price / 100000).toFixed(2)}L</span>
                  <span>{preset.max_power} bhp · {preset.vehicle_age}y</span>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main 3-Section Form */}
      <form onSubmit={onSubmit} className="space-y-8">

        {/* SECTION 1: Vehicle Identity */}
        <div className="bg-[#1C1E23] p-6 sm:p-7 rounded-sm border border-[rgba(244,243,240,0.08)]">
          <div className="flex items-center gap-2 mb-1">
            <CarFront className="w-4 h-4 text-[#38BDF8]" />
            <h2 className="font-serif-fraunces text-xl font-bold text-[#F4F3F0]">
              1. Vehicle Identity
            </h2>
          </div>
          <p className="text-xs text-[#8C8F94] mb-6">
            Make lineage, registration chronological age, and transmission drivetrain profile.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {/* Brand Dropdown (dynamically populated from le_brand.classes_) */}
            <div>
              <label htmlFor="brand" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Brand / Make <span className="text-[#38BDF8]">*</span>
              </label>
              <select
                id="brand"
                value={specs.brand}
                onChange={(e) => onChange('brand', e.target.value)}
                className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none transition-colors"
                required
              >
                {le_brand.classes_.map((brandName) => (
                  <option key={brandName} value={brandName}>
                    {brandName}
                  </option>
                ))}
              </select>
              <p className="text-[11px] text-[#8C8F94] mt-1">31 classes from encoder</p>
            </div>

            {/* Vehicle Age */}
            <div>
              <label htmlFor="vehicle_age" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Vehicle Age <span className="text-[#38BDF8]">*</span>
              </label>
              <div className="relative">
                <input
                  id="vehicle_age"
                  type="number"
                  min="0"
                  max="29"
                  step="1"
                  value={specs.vehicle_age}
                  onChange={(e) => onChange('vehicle_age', Math.max(0, Math.min(29, Number(e.target.value))))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  years
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Bounds: 0 to 29 years</p>
            </div>

            {/* Transmission Type (dynamically populated from le_trans.classes_) */}
            <div>
              <label htmlFor="transmission_type" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Transmission <span className="text-[#38BDF8]">*</span>
              </label>
              <select
                id="transmission_type"
                value={specs.transmission_type}
                onChange={(e) => onChange('transmission_type', e.target.value)}
                className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none transition-colors"
                required
              >
                {le_trans.classes_.map((trans) => (
                  <option key={trans} value={trans}>
                    {trans}
                  </option>
                ))}
              </select>
              <p className="text-[11px] text-[#8C8F94] mt-1">Automatic / Manual</p>
            </div>

            {/* Fuel Type (dynamically populated from le_fuel.classes_) */}
            <div>
              <label htmlFor="fuel_type" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Fuel Type <span className="text-[#38BDF8]">*</span>
              </label>
              <select
                id="fuel_type"
                value={specs.fuel_type}
                onChange={(e) => onChange('fuel_type', e.target.value)}
                className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none transition-colors"
                required
              >
                {le_fuel.classes_.map((fuel) => (
                  <option key={fuel} value={fuel}>
                    {fuel}
                  </option>
                ))}
              </select>
              <p className="text-[11px] text-[#8C8F94] mt-1">Petrol, Diesel, CNG, LPG, Electric</p>
            </div>
          </div>
        </div>

        <SpecSheetDivider label="SECTION // SPECIFICATION CONTINUUM" />

        {/* SECTION 2: Usage & Condition */}
        <div className="bg-[#1C1E23] p-6 sm:p-7 rounded-sm border border-[rgba(244,243,240,0.08)]">
          <div className="flex items-center gap-2 mb-1">
            <Gauge className="w-4 h-4 text-[#38BDF8]" />
            <h2 className="font-serif-fraunces text-xl font-bold text-[#F4F3F0]">
              2. Usage & Condition
            </h2>
          </div>
          <p className="text-xs text-[#8C8F94] mb-6">
            Odometer wear, fuel efficiency economy rating, and provenance sales channel.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            {/* Kilometers Driven */}
            <div>
              <label htmlFor="km_driven" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Distance Driven (km) <span className="text-[#38BDF8]">*</span>
              </label>
              <div className="relative">
                <input
                  id="km_driven"
                  type="number"
                  min="100"
                  max="3800000"
                  step="500"
                  value={specs.km_driven}
                  onChange={(e) => onChange('km_driven', Math.max(100, Number(e.target.value)))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  km
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Range: 100 to 3,800,000 km</p>
            </div>

            {/* Mileage (Fuel Economy) */}
            <div>
              <label htmlFor="mileage" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Certified Mileage <span className="text-[#38BDF8]">*</span>
              </label>
              <div className="relative">
                <input
                  id="mileage"
                  type="number"
                  min="4.0"
                  max="35.0"
                  step="0.1"
                  value={specs.mileage}
                  onChange={(e) => onChange('mileage', Math.max(1, Number(e.target.value)))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  km/l
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Fuel economy (km/l or km/kg)</p>
            </div>

            {/* Seller Type (dynamically populated from le_seller.classes_) */}
            <div>
              <label htmlFor="seller_type" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Seller Type <span className="text-[#38BDF8]">*</span>
              </label>
              <select
                id="seller_type"
                value={specs.seller_type}
                onChange={(e) => onChange('seller_type', e.target.value)}
                className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none transition-colors"
                required
              >
                {le_seller.classes_.map((seller) => (
                  <option key={seller} value={seller}>
                    {seller}
                  </option>
                ))}
              </select>
              <p className="text-[11px] text-[#8C8F94] mt-1">Dealer, Individual, Trustmark Dealer</p>
            </div>
          </div>
        </div>

        <SpecSheetDivider label="SECTION // MECHANICAL POWERTRAIN" />

        {/* SECTION 3: Engine Specification */}
        <div className="bg-[#1C1E23] p-6 sm:p-7 rounded-sm border border-[rgba(244,243,240,0.08)]">
          <div className="flex items-center gap-2 mb-1">
            <Wrench className="w-4 h-4 text-[#38BDF8]" />
            <h2 className="font-serif-fraunces text-xl font-bold text-[#F4F3F0]">
              3. Engine Specification
            </h2>
          </div>
          <p className="text-xs text-[#8C8F94] mb-6">
            Displacement volume, brake horsepower (RF dominant feature: 63.5%), and cabin cabin seating layout.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            {/* Engine Displacement (cc) */}
            <div>
              <label htmlFor="engine" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Engine Displacement <span className="text-[#38BDF8]">*</span>
              </label>
              <div className="relative">
                <input
                  id="engine"
                  type="number"
                  min="600"
                  max="6592"
                  step="1"
                  value={specs.engine}
                  onChange={(e) => onChange('engine', Math.max(500, Number(e.target.value)))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  cc
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Engine cylinder capacity in cc</p>
            </div>

            {/* Maximum Power (bhp) */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label htmlFor="max_power" className="block text-xs font-medium text-[#F4F3F0]">
                  Maximum Power <span className="text-[#38BDF8]">*</span>
                </label>
                <span className="text-[10px] font-mono text-[#1E6E4F] uppercase tracking-wider">
                  Key Predictor (63.5%)
                </span>
              </div>
              <div className="relative">
                <input
                  id="max_power"
                  type="number"
                  min="30"
                  max="650"
                  step="0.1"
                  value={specs.max_power}
                  onChange={(e) => onChange('max_power', Math.max(20, Number(e.target.value)))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[#38BDF8]/40 rounded px-3 py-2.5 focus:border-[#38BDF8] focus:ring-1 focus:ring-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  bhp
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Brake horsepower rating</p>
            </div>

            {/* Seats */}
            <div>
              <label htmlFor="seats" className="block text-xs font-medium text-[#F4F3F0] mb-1.5">
                Seating Capacity <span className="text-[#38BDF8]">*</span>
              </label>
              <div className="relative">
                <input
                  id="seats"
                  type="number"
                  min="2"
                  max="9"
                  step="1"
                  value={specs.seats}
                  onChange={(e) => onChange('seats', Math.max(2, Math.min(9, Number(e.target.value))))}
                  className="w-full bg-[#17181C] text-sm text-[#F4F3F0] border border-[rgba(244,243,240,0.18)] rounded px-3 py-2.5 focus:border-[#38BDF8] focus:outline-none font-mono transition-colors"
                  required
                />
                <span className="absolute right-3 top-2.5 text-xs text-[#8C8F94] font-mono pointer-events-none">
                  seats
                </span>
              </div>
              <p className="text-[11px] text-[#8C8F94] mt-1">Bounds: 2 to 9 (0 seats cleaned)</p>
            </div>
          </div>
        </div>

        {/* Action Button Bar */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 pt-4 border-t border-[rgba(244,243,240,0.12)]">
          <div className="text-xs text-[#8C8F94]">
            <span>Model: </span>
            <strong className="text-[#F4F3F0] font-mono">Random Forest Regressor (n_estimators=100)</strong>
            <span className="hidden sm:inline"> · Unscaled inputs</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={onReset}
              className="px-4 py-3 text-xs font-mono text-[#8C8F94] hover:text-[#F4F3F0] border border-[rgba(244,243,240,0.15)] rounded-sm hover:border-[rgba(244,243,240,0.3)] transition-colors cursor-pointer flex items-center justify-center gap-2"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Reset</span>
            </button>

            <button
              type="submit"
              disabled={isLoading}
              className="px-6 py-3 bg-[#0284C7] hover:bg-[#0EA5E9] text-white text-sm font-semibold rounded-sm tracking-wide transition-all shadow-md hover:shadow-lg cursor-pointer flex items-center justify-center gap-2"
            >
              <span>Estimate price</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};
